import { ICard, CardStatus } from 'src/models/card';
import {
  ITransaction,
  TransactionCategory,
  TransactionType,
} from 'src/models/transaction';

export const cards: ICard[] = [
  {
    id: 1,
    cardHolder: 'Matthew Mcmahon',
    cardNumber: '1234 1234 1234 1234',
    cvv: '123',
    expiryDate: '12/24',
    status: CardStatus.Active,
  },
  {
    id: 2,
    cardHolder: 'Matthew Mcmahon',
    cardNumber: '1111 1111 1111 1111',
    cvv: '123',
    expiryDate: '12/24',
    status: CardStatus.Inactive,
  },
  {
    id: 3,
    cardHolder: 'Matthew Mcmahon',
    cardNumber: '4321 4321 4321 4321',
    cvv: '123',
    expiryDate: '12/25',
    status: CardStatus.Active,
  },
];

export const transactions: ITransaction[] = [
  {
    id: 1,
    amount: 123,
    recipientName: 'Hamleys',
    currency: 'S$',
    type: TransactionType.Charged,
    transactionTime: new Date(2023, 1, 1),
    category: TransactionCategory.Travel,
    cardId: 1,
  },
  {
    id: 2,
    amount: 456,
    recipientName: 'Hamleys',
    currency: 'S$',
    type: TransactionType.Refund,
    transactionTime: new Date(2023, 2, 2),
    category: TransactionCategory.Grocery,
    cardId: 1,
  },
  {
    id: 3,
    amount: 1234,
    recipientName: 'Hamleys',
    currency: 'S$',
    type: TransactionType.Charged,
    transactionTime: new Date(2023, 3, 3),
    category: TransactionCategory.Payment,
    cardId: 1,
  },
  {
    id: 4,
    amount: 50,
    recipientName: 'KFC',
    currency: 'S$',
    type: TransactionType.Charged,
    transactionTime: new Date(2023, 3, 3),
    category: TransactionCategory.Payment,
    cardId: 1,
  },
  {
    id: 5,
    amount: 10000,
    recipientName: 'Dior',
    currency: 'S$',
    type: TransactionType.Charged,
    transactionTime: new Date(2023, 3, 3),
    category: TransactionCategory.Grocery,
    cardId: 2,
  },
  {
    id: 6,
    amount: 2000,
    recipientName: 'Vietnam Airline',
    currency: 'S$',
    type: TransactionType.Charged,
    transactionTime: new Date(2023, 3, 3),
    category: TransactionCategory.Payment,
    cardId: 3,
  },
  {
    id: 7,
    amount: 3000,
    recipientName: 'Vietnam Airline',
    currency: 'S$',
    type: TransactionType.Charged,
    transactionTime: new Date(2023, 3, 3),
    category: TransactionCategory.Payment,
    cardId: 3,
  },
];
